// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions]

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7RTpV_eVydTrbJvVdOUYr5n_jJMBjw0',
    appId: '1:180786396234:web:aef22a57b92f7886f3bab3',
    messagingSenderId: '180786396234',
    projectId: 'greenliving-presence',
    authDomain: 'greenliving-presence.firebaseapp.com',
    storageBucket: 'greenliving-presence.firebasestorage.app',
    measurementId: 'G-4531R0KBB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDOA4Gm-wkHbBjk9Rgm9z3Stnb21l4Lmk',
    appId: '1:180786396234:android:558c72de95093ecff3bab3',
    messagingSenderId: '180786396234',
    projectId: 'greenliving-presence',
    storageBucket: 'greenliving-presence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU1wuG0HiUq3DraiYjX0lj1EV8s6TC2H0',
    appId: '1:180786396234:ios:ebdb9d5f21527b22f3bab3',
    messagingSenderId: '180786396234',
    projectId: 'greenliving-presence',
    storageBucket: 'greenliving-presence.firebasestorage.app',
    iosBundleId: 'com.example.absensiGreenliving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU1wuG0HiUq3DraiYjX0lj1EV8s6TC2H0',
    appId: '1:180786396234:ios:ebdb9d5f21527b22f3bab3',
    messagingSenderId: '180786396234',
    projectId: 'greenliving-presence',
    storageBucket: 'greenliving-presence.firebasestorage.app',
    iosBundleId: 'com.example.absensiGreenliving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7RTpV_eVydTrbJvVdOUYr5n_jJMBjw0',
    appId: '1:180786396234:web:4901d123c742a30af3bab3',
    messagingSenderId: '180786396234',
    projectId: 'greenliving-presence',
    authDomain: 'greenliving-presence.firebaseapp.com',
    storageBucket: 'greenliving-presence.firebasestorage.app',
    measurementId: 'G-6T9QVR360X',
  );

}